/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.danielGUI;

import com.daniel.me.biz.Golosina;
import com.daniel.me.biz.MaquinaExpendedora;
import com.daniel.metodos.Metodos;
import com.daniel.utils.exceptions.EmptyPositionException;
import com.daniel.utils.exceptions.IncorrectPositionException;
import com.daniel.utils.exceptions.InsufficientMoney;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dev
 */
public class ExecGUI extends javax.swing.JFrame {

    private MaquinaExpendedora maq = null;
    Metodos me = new Metodos();

    /**
     * Creates new form ExecGUI
     */
    public ExecGUI() {
        initComponents();
    }

    public MaquinaExpendedora getMaq() {
        return maq;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecGUI().setVisible(true);

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1Titulo = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTiposGolosinas = new javax.swing.JTable();
        jButton2€ = new javax.swing.JButton();
        jButton1€ = new javax.swing.JButton();
        jButton50Cent = new javax.swing.JButton();
        jButton20Cent = new javax.swing.JButton();
        jButton10cent = new javax.swing.JButton();
        jButton5cent = new javax.swing.JButton();
        jButtonBorrado = new javax.swing.JButton();
        jButtonNumero1 = new javax.swing.JButton();
        jButtonNumero2 = new javax.swing.JButton();
        jButtonNumero3 = new javax.swing.JButton();
        jButtonNumero4 = new javax.swing.JButton();
        jButtonNumero5 = new javax.swing.JButton();
        jButtonNumero6 = new javax.swing.JButton();
        jButtonNumero7 = new javax.swing.JButton();
        jButtonNumero8 = new javax.swing.JButton();
        jButtonNumero9 = new javax.swing.JButton();
        jButtonNumero0 = new javax.swing.JButton();
        jButtonLetraA = new javax.swing.JButton();
        jButtonLetraB = new javax.swing.JButton();
        jButtonLetraC = new javax.swing.JButton();
        jButtonLetraD = new javax.swing.JButton();
        jTextFieldDineroInsertado = new javax.swing.JTextField();
        jTextField1Posicion = new javax.swing.JTextField();
        jButton1Devolucion = new javax.swing.JButton();
        jButton2Pedir = new javax.swing.JButton();
        jButtonAdministrar = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();
        jTextField1Respuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextPane1Titulo.setEditable(false);
        jTextPane1Titulo.setText("MÁQUINA EXPENDEDORA");
        jTextPane1Titulo.setFocusable(false);
        jScrollPane1.setViewportView(jTextPane1Titulo);

        jTableTiposGolosinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Cantidad", "Posición"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTiposGolosinas.setFocusable(false);
        jTableTiposGolosinas.getTableHeader().setReorderingAllowed(false);
        jTableTiposGolosinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTiposGolosinasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTiposGolosinas);

        jButton2€.setText("2€");
        jButton2€.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2€ActionPerformed(evt);
            }
        });

        jButton1€.setText("1€");
        jButton1€.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1€ActionPerformed(evt);
            }
        });

        jButton50Cent.setText("0,50€");
        jButton50Cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50CentActionPerformed(evt);
            }
        });

        jButton20Cent.setText("0,20€");
        jButton20Cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20CentActionPerformed(evt);
            }
        });

        jButton10cent.setText("0,10€");
        jButton10cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10centActionPerformed(evt);
            }
        });

        jButton5cent.setText("0,05€");
        jButton5cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5centActionPerformed(evt);
            }
        });

        jButtonBorrado.setText("<--");
        jButtonBorrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorradoActionPerformed(evt);
            }
        });

        jButtonNumero1.setText("1");
        jButtonNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero1ActionPerformed(evt);
            }
        });

        jButtonNumero2.setText("2");
        jButtonNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero2ActionPerformed(evt);
            }
        });

        jButtonNumero3.setText("3");
        jButtonNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero3ActionPerformed(evt);
            }
        });

        jButtonNumero4.setText("4");
        jButtonNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero4ActionPerformed(evt);
            }
        });

        jButtonNumero5.setText("5");
        jButtonNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero5ActionPerformed(evt);
            }
        });

        jButtonNumero6.setText("6");
        jButtonNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero6ActionPerformed(evt);
            }
        });

        jButtonNumero7.setText("7");
        jButtonNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero7ActionPerformed(evt);
            }
        });

        jButtonNumero8.setText("8");
        jButtonNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero8ActionPerformed(evt);
            }
        });

        jButtonNumero9.setText("9");
        jButtonNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero9ActionPerformed(evt);
            }
        });

        jButtonNumero0.setText("0");
        jButtonNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumero0ActionPerformed(evt);
            }
        });

        jButtonLetraA.setText("A");
        jButtonLetraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLetraAActionPerformed(evt);
            }
        });

        jButtonLetraB.setText("B");
        jButtonLetraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLetraBActionPerformed(evt);
            }
        });

        jButtonLetraC.setText("C");
        jButtonLetraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLetraCActionPerformed(evt);
            }
        });

        jButtonLetraD.setText("D");
        jButtonLetraD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLetraDActionPerformed(evt);
            }
        });

        jTextFieldDineroInsertado.setEditable(false);
        jTextFieldDineroInsertado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDineroInsertadoActionPerformed(evt);
            }
        });

        jTextField1Posicion.setEditable(false);

        jButton1Devolucion.setText("Devolver");
        jButton1Devolucion.setToolTipText("");
        jButton1Devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1DevolucionActionPerformed(evt);
            }
        });

        jButton2Pedir.setText("Pedir");
        jButton2Pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2PedirActionPerformed(evt);
            }
        });

        jButtonAdministrar.setText("Administrar");
        jButtonAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdministrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2€, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1€, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton50Cent))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton20Cent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDineroInsertado))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton10cent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1Posicion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonBorrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5cent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButtonNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2Pedir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonLetraA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonLetraB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonLetraC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButtonLetraD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonAdministrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1Devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2€, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1€, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton50Cent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton10cent, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton5cent, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton20Cent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1Posicion, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                        .addComponent(jButtonBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldDineroInsertado))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLetraA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1Respuesta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLetraB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLetraC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLetraD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2Pedir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1Devolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdministrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarDatos() {
        DefaultTableModel m = (DefaultTableModel) this.jTableTiposGolosinas.getModel();
        m.setNumRows(0);
        try {
            ArrayList<Golosina> gs = maq.devuelveGolosina();
            for (Golosina g : gs) {
                String format = String.format("%.2f", g.getPrecio());
                Object[] o = {g.getNombre(), format, g.getCantidad(), g.getPosicion()};
                m.addRow(o);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            this.jTextField1Respuesta.setText("Se ha producido un error " + ex.getMessage());
        }
    }
    private void jButton1€ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1€ActionPerformed
        // TODO add your handling code here:
        maq.setMonedero(me.redondeoDosNumeros(maq.getMonedero() + 1));
        String format = String.format("%.2f", maq.getMonedero());
        this.jTextFieldDineroInsertado.setText(format);
    }//GEN-LAST:event_jButton1€ActionPerformed

    private void jButton50CentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50CentActionPerformed
        // TODO add your handling code here:
        maq.setMonedero(me.redondeoDosNumeros(maq.getMonedero() + 0.50));
        String format = String.format("%.2f", maq.getMonedero());
        this.jTextFieldDineroInsertado.setText(format);
    }//GEN-LAST:event_jButton50CentActionPerformed

    private void jButton10centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10centActionPerformed
        // TODO add your handling code here:
        maq.setMonedero(me.redondeoDosNumeros(maq.getMonedero() + 0.10));
        String format = String.format("%.2f", maq.getMonedero());
        this.jTextFieldDineroInsertado.setText(format);
    }//GEN-LAST:event_jButton10centActionPerformed

    private void jButtonNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero8ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "8");
    }//GEN-LAST:event_jButtonNumero8ActionPerformed

    private void jButtonBorradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorradoActionPerformed
        // TODO add your handling code here:
        if (this.jTextField1Posicion.getText().length() != 0) {
            this.jTextField1Posicion.setText(jTextField1Posicion.getText().substring(0, jTextField1Posicion.getText().length() - 1));
        }
    }//GEN-LAST:event_jButtonBorradoActionPerformed

    private void jButton2€ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2€ActionPerformed
        // TODO add your handling code here:
        maq.setMonedero(me.redondeoDosNumeros(maq.getMonedero() + 2));
        String format = String.format("%.2f", maq.getMonedero());
        this.jTextFieldDineroInsertado.setText(format);
    }//GEN-LAST:event_jButton2€ActionPerformed

    private void jButton20CentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20CentActionPerformed
        // TODO add your handling code here:
        maq.setMonedero(me.redondeoDosNumeros(maq.getMonedero() + 0.20));
        String format = String.format("%.2f", maq.getMonedero());
        this.jTextFieldDineroInsertado.setText(format);
    }//GEN-LAST:event_jButton20CentActionPerformed

    private void jButton5centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5centActionPerformed
        // TODO add your handling code here:
        maq.setMonedero(me.redondeoDosNumeros(maq.getMonedero() + 0.05));
        String format = String.format("%.2f", maq.getMonedero());
        this.jTextFieldDineroInsertado.setText(format);
    }//GEN-LAST:event_jButton5centActionPerformed

    private void jTextFieldDineroInsertadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDineroInsertadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDineroInsertadoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            this.maq = new MaquinaExpendedora();
            cargarDatos();
            this.jTextField1Respuesta.setText("   Bienvenido   Welcome    Bienvenu     Benvenuto   ");

        } catch (Exception ex) {
            this.jTextField1Respuesta.setText("Se ha producido un error " + ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButtonNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero1ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "1");

    }//GEN-LAST:event_jButtonNumero1ActionPerformed

    private void jButtonNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero2ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "2");
    }//GEN-LAST:event_jButtonNumero2ActionPerformed

    private void jButtonNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero3ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "3");
    }//GEN-LAST:event_jButtonNumero3ActionPerformed

    private void jButtonNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero4ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "4");
    }//GEN-LAST:event_jButtonNumero4ActionPerformed

    private void jButtonNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero5ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "5");
    }//GEN-LAST:event_jButtonNumero5ActionPerformed

    private void jButtonNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero6ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "6");
    }//GEN-LAST:event_jButtonNumero6ActionPerformed

    private void jButtonNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero7ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "7");
    }//GEN-LAST:event_jButtonNumero7ActionPerformed

    private void jButtonNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero9ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "9");
    }//GEN-LAST:event_jButtonNumero9ActionPerformed

    private void jButtonNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero0ActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "0");
    }//GEN-LAST:event_jButtonNumero0ActionPerformed

    private void jButtonLetraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLetraAActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "A");
    }//GEN-LAST:event_jButtonLetraAActionPerformed

    private void jButtonLetraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLetraBActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "B");
    }//GEN-LAST:event_jButtonLetraBActionPerformed

    private void jButtonLetraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLetraCActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "C");
    }//GEN-LAST:event_jButtonLetraCActionPerformed

    private void jButtonLetraDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLetraDActionPerformed
        // TODO add your handling code here:
        this.jTextField1Posicion.setText(this.jTextField1Posicion.getText() + "D");
    }//GEN-LAST:event_jButtonLetraDActionPerformed

    private void jButton1DevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1DevolucionActionPerformed
        // TODO add your handling code here:
        this.jTextFieldDineroInsertado.setText("");
        this.jTextField1Respuesta.setText("Se te ha devuelto el dinero: " + maq.getMonedero() + "€");
        maq.setMonedero(0);
    }//GEN-LAST:event_jButton1DevolucionActionPerformed

    private void jButton2PedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2PedirActionPerformed
        double devuelto;
        try {
            // TODO add your handling code here:
            Golosina g = maq.pedirGolosina(this.jTextField1Posicion.getText());
            if (g != null) {
                if (maq.getMonedero() == me.redondeoDosNumeros(g.getPrecio())) {
                    this.jTextField1Respuesta.setText("Se ha realizado la compra correctamente");
                } else if (maq.getMonedero() > g.getPrecio()) {
                    devuelto = maq.getMonedero() - g.getPrecio();
                    this.jTextField1Respuesta.setText("Compra realizada correctamente. Se te ha devuelto " + me.redondeoDosNumeros(devuelto) + "€");
                }
                if (g.getPosicion().equals("0A")) {
                    this.jLabelImagen.setIcon(new ImageIcon("./cerveza.jpg"));
                } else if (g.getPosicion().equals("6A")) {
                    this.jLabelImagen.setIcon(new ImageIcon("./aquarius.jpg"));
                } else if (g.getPosicion().equals("5A")) {
                    this.jLabelImagen.setIcon(new ImageIcon("./cocacola.jpg"));
                } else if (g.getPosicion().equals("5B")) {
                    this.jLabelImagen.setIcon(new ImageIcon("./fantalimon.jpeg"));
                } else if (g.getPosicion().equals("5C")) {
                    this.jLabelImagen.setIcon(new ImageIcon("./fantanaranja.jpg"));
                } else if (g.getPosicion().equals("5D")) {
                    this.jLabelImagen.setIcon(new ImageIcon("./nestea.jpg"));
                }
                maq.setMonedero(0);
                this.jTextFieldDineroInsertado.setText(null);
                this.jTextField1Posicion.setText(null);
                cargarDatos();
            }
        } catch (IncorrectPositionException ex) {
            this.jTextField1Respuesta.setText("Posición incorrecta, no existe esa posición");
            this.jLabelImagen.setIcon(null);
        } catch (EmptyPositionException ex) {
            this.jTextField1Respuesta.setText("No quedan. Pide otra cosa o solicita la devolución");
            this.jLabelImagen.setIcon(null);
        } catch (InsufficientMoney ex) {
            this.jTextField1Respuesta.setText("Dinero Insuficiente. Añade más dinero o solicita la devolución.");
            this.jLabelImagen.setIcon(null);
        } catch (SQLException ex) {
            this.jTextField1Respuesta.setText("Error al recuperar datos ");
            this.jLabelImagen.setIcon(null);
        } catch (Exception ex) {
            ex.printStackTrace();
            this.jTextField1Respuesta.setText("No se ha podido realizar la compra");
            this.jLabelImagen.setIcon(null);
        }
    }//GEN-LAST:event_jButton2PedirActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            maq.guardarDatos();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButtonAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministrarActionPerformed
        // TODO add your handling code here:
        Aux dAux = new Aux(this, true);
        dAux.setVisible(true);
    }//GEN-LAST:event_jButtonAdministrarActionPerformed

    private void jTableTiposGolosinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTiposGolosinasMouseClicked
        // TODO add your handling code here:
        String posicion = this.jTableTiposGolosinas.getValueAt(this.jTableTiposGolosinas.getSelectedRow(), 3).toString();
        this.jTextField1Posicion.setText(posicion);
    }//GEN-LAST:event_jTableTiposGolosinasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10cent;
    private javax.swing.JButton jButton1Devolucion;
    private javax.swing.JButton jButton1€;
    private javax.swing.JButton jButton20Cent;
    private javax.swing.JButton jButton2Pedir;
    private javax.swing.JButton jButton2€;
    private javax.swing.JButton jButton50Cent;
    private javax.swing.JButton jButton5cent;
    private javax.swing.JButton jButtonAdministrar;
    private javax.swing.JButton jButtonBorrado;
    private javax.swing.JButton jButtonLetraA;
    private javax.swing.JButton jButtonLetraB;
    private javax.swing.JButton jButtonLetraC;
    private javax.swing.JButton jButtonLetraD;
    private javax.swing.JButton jButtonNumero0;
    private javax.swing.JButton jButtonNumero1;
    private javax.swing.JButton jButtonNumero2;
    private javax.swing.JButton jButtonNumero3;
    private javax.swing.JButton jButtonNumero4;
    private javax.swing.JButton jButtonNumero5;
    private javax.swing.JButton jButtonNumero6;
    private javax.swing.JButton jButtonNumero7;
    private javax.swing.JButton jButtonNumero8;
    private javax.swing.JButton jButtonNumero9;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTiposGolosinas;
    private javax.swing.JTextField jTextField1Posicion;
    private javax.swing.JLabel jTextField1Respuesta;
    private javax.swing.JTextField jTextFieldDineroInsertado;
    private javax.swing.JTextPane jTextPane1Titulo;
    // End of variables declaration//GEN-END:variables
}
